### PR TITLE
Path fix

### PR DESCRIPTION
**Pull request by complynx**
If not for this, on my machine with MinGW in %PATH% this won't work

### CODE REVIEW

**Comment by grompe** [comment]
I don't understand what are you trying to fix here.

What doesn't work?

What's in your PATH?

**Comment by complynx** [comment]
"find" is also part of MinGW (as ★NIX utility), and has slightly different API.
And MinGW path may appear before system. Or Cygwin, or git, or any other MinGW/Cygwin/★NIX based installation.

**Comment by complynx** [comment]
F★ck stars

**Comment by complynx** [comment]
`Microsoft Windows [Version 10.0.10586]
(c) Корпорация Майкрософт (Microsoft Corporation), 2015. Все права защищены.

C:\Users\complynx>where find
d:\MinGW\msys\1.0\bin\find.exe
C:\Windows\System32\find.exe

C:\Users\complynx>`

**Comment by grompe** [comment]
Is that MinGW default behavior?

Because I'm inclined to say that if you're overriding system32 programs, you're going to have a problem with more .bat files than just mine.

Anyway, I'll put a workaround for this, thanks!

**Comment by complynx** [comment]
I don't remember exactly, which of the mentioned installations has these modifiers, yet certainly there are some which have a checkbox for that. Maybe I should've just moved these paths to the back of my PATH. It will be Ok, if MinGW prepends it's own paths on startup correctly. Otherwise I'd rather leave it as is, because I use nix commands and env far more often, than pure cmd. Yet now I know that and would be more careful with bat's next time.
Also to say, there is a move in Windows dev team to provide smooth execution of unix code on win, based on cygwin environment, and it might appear in the path as well, before SYSTEM (though I can't test that, I'm not assigned to MS preview builds)

**Pull request closed without merging**
